"""
Step1_initialize.py  (CORRECTED)
=====================================================================
Python translation of Step_1_Initialize_SERPENT_Inversion.m for 1D
marine / land MT Bayesian inversion.

Fixes vs. the original Step1_initialize.py
------------------------------------------
1. Uses MT.read_edi() (units-correct EDI reader with proper TM-phase
   unwrapping) instead of MT.readEDI+z2rhophy which had a units bug
   (rho_a was ~C^2 ~ 633k times too small).
2. `landData` is ALWAYS initialised before the if-branch so the
   marine case (water_depth >= 1) no longer crashes with NameError.
3. Adds explicit user overrides for water_depth and landData so you
   are not at the mercy of `REFELEV=0.0` in the EDI header.
4. The data figure is written AFTER os.makedirs(out_dir) so it
   actually lands in Trash/ (the previous version silently saved it
   to the current working directory).
5. Default `numIterations`/`saveEvery` tuned for real runs but
   accessible via the parameter block at the top.

Produces three pickle files in <out_dir>/ that Step 2 consumes:
    <FileNameRoot>.pkl    - main S structure
    WaterColumn.pkl       - S1 (water-column) structure
    Subsurface.pkl        - S2 (subsurface) structure
=====================================================================
"""

# --------------------------
# FORCE NON-INTERACTIVE PLOT BACKEND (BEFORE ANY PLT IMPORT!)
# --------------------------
import os
import matplotlib
matplotlib.use('Agg')  # This must come BEFORE importing matplotlib.pyplot!
import matplotlib.pyplot as plt
import pickle
import numpy as np

# units-correct EDI reader from MT
from MT import read_edi, edi_to_S_MTdat, read_mt_mare2dem

# =====================================================================
# USER-EDITABLE PARAMETERS
# =====================================================================
FileNameRoot = 's08_TM'
out_dir      = 'Trash'
edi_path     = 'SERPENT_fullMTdataSet.txt'

# For Mare2DEM-format MT files (e.g. SERPENT_fullMTdataSet.txt) which
# contain MANY stations in one file, set the station to extract.  Leave
# at None for single-station EDI files.
station_name = 's08'

# --- Mode --------------------------------------------------------------
# Set EXACTLY one of TE/TM to True
# TE = Zxy mode (E-field along strike);  TM = Zyx mode (E-field across strike)
TE, TM = False, True

# --- Site geometry (manual overrides) ---------------------------------
# Set to None to auto-read from EDI's REFELEV.  If you know the actual
# water depth, set it here in METRES (positive number).
water_depth_override = None        # EM5 has REFELEV=-3086 so auto works
# Set True for land station, False for marine, None for auto-detect
# (auto: water_depth_override < 1 m  ==>  land).
landData_override    = None        # auto: REFELEV=-3086 -> marine

# --- Error floors ------------------------------------------------------
phase_err_floor   = 2.0            # deg
app_res_err_floor = 0.05           # fractional (will be / log10 inside)

# --- Which data types to forward-model --------------------------------
ST, OB, MT_flag, DCR = False, False, True, False

# --- Inversion options -------------------------------------------------
fixedDimension = False
fixedWater     = False
logZ           = True
transform01_ab = False
debug_prior    = False
jeffereys_prior= False

# --- Depth-dependent maximum-resistivity prior (Blatter 2022 style) ---
# Set to a path to a 2-column ASCII file `depth_km   log10_rho_max`
# (e.g. 'maxrho_1300C_MPT.txt' generated by make_maxrho_1300C_MPT.py)
# to use a depth-dependent upper bound rather than the flat S2.rhoMax=5
# cap.  Set to None to keep the scalar bound (legacy behaviour).
rho_max_profile_path = 'maxrho_1300C_MPT.txt'

# --- PT-RJMCMC parameters ---------------------------------------------
nTemps         = 6
nChainsAt1     = 3
nChains        = nTemps + nChainsAt1 - 1     # = 8
Tmax           = 2.0
numIterations  = int(1e5)         # 1e5 is a realistic minimum for production
saveEvery      = int(1e4)         # save 10x during the run
displayEvery   = 200
ARwindow       = 500
beta           = 0.0              # P(perturb water column)

# --- Multi-chain parallelisation --------------------------------------
# n_workers controls how many worker processes run the per-iteration
# chain steps.  Default `'auto'` picks the best value for the data
# configuration declared above (ST / OB / MT_flag / DCR):
#
#   CSEM (ST or OB True) ->  min(8, nChains)
#       empymod forward calls are ~10-300 ms each, so the IPC overhead
#       (~5 ms/call) is small compared with the work parallelised.
#
#   MT / DCR only         ->  1  (serial)
#       analytical MT / DCR forwards are ~1 ms; spawning workers would
#       cost MORE than the work itself.
#
# You can also set an explicit int (1 = legacy serial, n>1 = parallel).
# Requires Linux fork() to inherit the registered empymod / dipole1d
# forward solvers; on macOS / Windows you'd have to register them
# inside each worker.
n_workers      = 'auto'           # 'auto' | 1 | 2 | 4 | 8 | ...
seed           = None             # set an int for reproducible runs

# resolve 'auto' -> integer ----------------------------------------------
if isinstance(n_workers, str) and n_workers.lower() == 'auto':
    has_csem = bool(ST or OB)
    n_workers = min(8, nChains) if has_csem else 1
    print(f"  [auto] dataTypes=[ST={ST}, OB={OB}, MT={MT_flag}, DCR={DCR}] "
          f"-> n_workers = {n_workers}")

# Whether to pop the data window (set False if running headless)
show_plot      = False


# =====================================================================
def main():

    if TE and TM:
        raise SystemExit("Set exactly one of TE / TM to True.")
    if not (TE or TM):
        raise SystemExit("Set one of TE / TM to True.")

    # 0. Create out_dir early so plots and pickles land there ---------
    os.makedirs(out_dir, exist_ok=True)

    # 1. Read MT data (EDI or Mare2DEM multi-station .txt) -----------
    is_mare2dem = (station_name is not None) or \
                  edi_path.lower().endswith(('.txt', '.resp', '.dat'))
    if is_mare2dem:
        if station_name is None:
            raise SystemExit("For Mare2DEM multi-station files, set "
                             "station_name (e.g. 's08').")
        MTdata = read_mt_mare2dem(edi_path,
                                  station_name      = station_name,
                                  app_res_err_floor = app_res_err_floor,
                                  phase_err_floor   = phase_err_floor,
                                  unwrap_tm_phase   = True,
                                  verbose           = True)
    else:
        MTdata = read_edi(edi_path,
                          water_depth     = water_depth_override,
                          units           = 'field',
                          te_mode         = 'xy',
                          app_res_err_floor = app_res_err_floor,
                          phase_err_floor   = phase_err_floor,
                          unwrap_tm_phase = True,
                          verbose         = True)

    # Pull TE or TM block out of the combined MTdata dict
    mode = 'TM' if TM else 'TE'
    Sdat = edi_to_S_MTdat(MTdata, mode=mode)

    # 2. Decide land vs. marine ----------------------------------------
    water_depth = float(MTdata['WaterDepth'])      # populated from EDI

    # ALWAYS initialise landData first -- this fixes the NameError bug
    landData = False
    if landData_override is not None:
        landData = bool(landData_override)
        if landData and water_depth < 1.0:
            water_depth = 0.1
    else:
        if water_depth < 1.0:
            print('[INFO] water depth < 1 m  ==>  treating as LAND data.')
            print('       (override with landData_override=False if this'
                  ' is a marine site whose EDI lost its REFELEV.)')
            landData    = True
            water_depth = 0.1

    print(f'  landData = {landData}    water depth = {water_depth} m')

    # 3. Build S structure ---------------------------------------------
    S = {
        'MTdat': {
            'TEappRes':    Sdat.TEappRes,
            'TEappResErr': Sdat.TEappResErr,
            'TEphase':     Sdat.TEphase,
            'TEphaseErr':  Sdat.TEphaseErr,
            'freqs':       Sdat.freqs,
        },
        'Tx':                 {'WaterDepth': water_depth},
        'regionBoundaryDepth': water_depth,
        'dataTypes':          np.array([ST, OB, MT_flag, DCR], dtype=bool),
        'fixedDimension':     fixedDimension,
        'fixedWater':         fixedWater,
        'debug_prior':        debug_prior,
        'jeffereys_prior':    jeffereys_prior,
        'transform01_ab':     transform01_ab,
        'logZ':               logZ,
        'landData':           landData,
        'nTemps':             nTemps,
        'nChains':            nChains,
        'nChainsAtOne':       nChainsAt1,
        'Tmax':               Tmax,
        'B':                  np.concatenate([
                                  np.logspace(-np.log10(Tmax), 0, nTemps),
                                  np.ones(nChains - nTemps),
                              ]),
        'numIterations':      numIterations,
        'saveEvery':          saveEvery,
        'displayEvery':       displayEvery,
        'ARwindow':           ARwindow,
        'beta':               beta,
        'n_workers':          n_workers,
        'seed':               seed,
        'FileNameRoot':       FileNameRoot,
    }

    # 4. Water-column S1 -----------------------------------------------
    if landData:
        # No water column to invert -- placeholder values
        S1 = dict(
            birth_death_from_prior = True,
            isotropic              = True,
            kInit                  = 0,
            kMin                   = 0,
            kMax                   = 0,
            zMin                   = 0.1,
            zMax                   = 1.0,
            rhoMin                 = -0.523,
            rhoMax                 = -0.520,
        )
    else:
        S1 = dict(
            birth_death_from_prior = True,
            isotropic              = True,
            kInit                  = 1,
            kMin                   = 1,
            kMax                   = 7,
            zMin                   = 0.1,
            zMax                   = S['regionBoundaryDepth'],
            rhoMin                 = -0.75,
            rhoMax                 = -0.55,
        )
    if logZ:
        S1['zMin'] = np.log10(S1['zMin'])
        S1['zMax'] = np.log10(S1['zMax'])
    S1['UstepSize'] = np.concatenate([
        np.linspace(0.02, 0.002, nTemps),
        0.002 * np.ones(nChains - nTemps)])
    S1['BstepSize'] = np.concatenate([
        np.linspace(0.05, 0.025, nTemps),
        0.025 * np.ones(nChains - nTemps)])
    M1 = np.concatenate([np.linspace(4.0, 1.5, nTemps),
                         1.5 * np.ones(nChains - nTemps)])
    if logZ:
        M1 = np.log10(M1)
    S1['MstepSize'] = M1

    # 5. Subsurface S2 -------------------------------------------------
    S2 = dict(
        birth_death_from_prior = True,
        isotropic              = True,
        kInit                  = 1,
        kMin                   = 1,
        kMax                   = 50,
        zMin                   = S['regionBoundaryDepth'],
        zMax                   = 135_000.0,
        rhoMin                 = -1.0,
        rhoMax                 = 5.0,
    )
    if logZ:
        S2['zMin']               = np.log10(S2['zMin'])
        S2['zMax']               = np.log10(S2['zMax'])
        S['regionBoundaryDepth'] = np.log10(S['regionBoundaryDepth'])
    if transform01_ab:
        S2['rhoMin'], S2['rhoMax'] = 0.0, 1.0
        S['zMin'] = S2['zMin']; S['zMax'] = S2['zMax']
    else:
        S['prior'] = 1.0 / (S2['rhoMax'] - S2['rhoMin'])

    # ---- depth-dependent upper bound on log10(rho_max) ---------------
    # If `rho_max_profile_path` is set we load a (depth_km, log10_rho_max)
    # txt file (e.g. maxrho_1300C_MPT.txt -- the dry-olivine cap used in
    # Blatter et al. 2022) and attach it to BOTH S2 (subsurface params)
    # and the master S so that PT_RJMCMC can read it.  S2['rhoMax']
    # stays as the global scalar ceiling so any code path that does
    # not call _rhoMaxAt() degrades cleanly.
    # The profile is interpreted in ABSOLUTE depth below the seafloor
    # (or below the surface for land data).  It is depth-INDEPENDENT
    # of logZ / transform01_ab.
    if rho_max_profile_path is not None:
        from rjmcmc_inversion import load_rho_max_profile
        z_km_p, rmax_p = load_rho_max_profile(rho_max_profile_path)
        # store as plain numpy arrays so pickling is portable
        S2['rhoMaxProfile']      = (z_km_p, rmax_p)
        S2['rhoMaxProfilePath']  = rho_max_profile_path
        S['rhoMaxProfilePath']   = rho_max_profile_path
        # _rhoMaxAt(z_inv, S2) needs to know whether z_inv is in log10
        # space (S2.logZ) and where the seafloor is (regionBoundaryDepth)
        # so it can convert the inversion coord into "km below seafloor".
        # Both already live on the master S, copy onto S2 so PT_RJMCMC
        # (which only sees S_2 inside _birth / _rhoUpdate) can do the
        # conversion locally.
        S2['logZ']               = logZ
        S2['regionBoundaryDepth'] = S['regionBoundaryDepth']
        print(f'  rho-max profile     = {rho_max_profile_path}  '
              f'({len(z_km_p)} depths, range '
              f'log10(rho_max)=[{rmax_p.min():.2f}, {rmax_p.max():.2f}])')

    S2['UstepSize'] = np.concatenate([
        np.linspace(0.006, 0.001, nTemps),
        0.001 * np.ones(nChains - nTemps)])
    S2['BstepSize'] = np.concatenate([
        np.linspace(0.6, 0.4, nTemps),
        0.4 * np.ones(nChains - nTemps)])
    M2 = np.concatenate([np.linspace(25.0, 7.0, nTemps),
                         7.0 * np.ones(nChains - nTemps)])
    if logZ:
        M2 = np.log10(M2)
    S2['MstepSize'] = M2

    # 6. Plot the data --------------------------------------------------
    plot_path = _plot_mt_data(S['MTdat'], FileNameRoot, out_dir,
                              show=show_plot)

    # 7. Write the three pickles ---------------------------------------
    # Clean any previous run's outputs to mimic MATLAB's "!rm Trash/* ."
    for fname in os.listdir(out_dir):
        fp = os.path.join(out_dir, fname)
        if os.path.isfile(fp) and fname.endswith('.pkl'):
            os.remove(fp)

    main_fp = os.path.join(out_dir, FileNameRoot + '.pkl')
    wc_fp   = os.path.join(out_dir, 'WaterColumn.pkl')
    sub_fp  = os.path.join(out_dir, 'Subsurface.pkl')
    with open(main_fp, 'wb') as fh: pickle.dump(S,  fh)
    with open(wc_fp,   'wb') as fh: pickle.dump(S1, fh)
    with open(sub_fp,  'wb') as fh: pickle.dump(S2, fh)

    print('\nStep 1 complete.  Wrote:')
    print(' ', main_fp)
    print(' ', wc_fp)
    print(' ', sub_fp)
    print(' ', plot_path)
    print(f"\n  WaterDepth          = {S['Tx']['WaterDepth']:g} m")
    print(f"  regionBoundaryDepth = {S['regionBoundaryDepth']:g}  "
          f"({'log10' if logZ else 'linear'} m)")
    print(f"  nFreqs              = {len(S['MTdat']['freqs'])}")
    print(f"  log10(rho_a) range  = [{S['MTdat']['TEappRes'].min():.2f}, "
          f"{S['MTdat']['TEappRes'].max():.2f}]")
    print(f"  phase range         = [{S['MTdat']['TEphase'].min():.1f}, "
          f"{S['MTdat']['TEphase'].max():.1f}] deg")
    print(f"  mode                = {mode}")
    print(f"  landData            = {landData}")
    print(f"  nChains / nTemps    = {nChains} / {nTemps}")
    print(f"  B ladder            = {np.round(S['B'], 3)}")
    print('\n  Proceed to Step 2 (run the inversion).')


# ---------------------------------------------------------------------
def _plot_mt_data(MTdat, title, out_dir, show=False):
    T = 1.0 / MTdat['freqs']

    fig, ax = plt.subplots(2, 1, figsize=(7.5, 7.5), sharex=True)

    ax[0].errorbar(T, MTdat['TEappRes'], yerr=MTdat['TEappResErr'],
                   fmt='o', color='C3', mfc='C3', mec='k',
                   ecolor='k', capsize=2, linewidth=1.4)
    ax[0].set_xscale('log')
    ax[0].set_ylabel(r'$\log_{10}\rho_a$  (ohm$\cdot$m)')
    ax[0].set_title(f'{title}: apparent resistivity')
    ax[0].grid(True, which='both', alpha=0.3)

    ax[1].errorbar(T, MTdat['TEphase'], yerr=MTdat['TEphaseErr'],
                   fmt='o', color='C3', mfc='C3', mec='k',
                   ecolor='k', capsize=2, linewidth=1.4)
    ax[1].set_xscale('log')
    ax[1].set_xlabel('Period (s)')
    ax[1].set_ylabel('Phase (deg)')
    ax[1].set_title(f'{title}: phase')
    pmin, pmax = float(np.nanmin(MTdat['TEphase'])), float(np.nanmax(MTdat['TEphase']))
    ymin = min(0,  pmin - 5)
    ymax = max(90, pmax + 5)
    ax[1].set_ylim(ymin, ymax)
    ax[1].grid(True, which='both', alpha=0.3)

    fig.tight_layout()
    save_path = os.path.join(out_dir, title + '_data.png')
    fig.savefig(save_path, dpi=120, bbox_inches='tight')
    print(f'[INFO] Data plot saved to {save_path}')
    if show:
        plt.show()
    plt.close(fig)
    return save_path


# ---------------------------------------------------------------------
if __name__ == '__main__':
    main()
